# Configuration file for the Sphinx documentation builder.
#
# This file only contains a selection of the most common options. For a full
# list see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
# import os
# import sys
# sys.path.insert(0, os.path.abspath('.'))


# -- Project information -----------------------------------------------------

project = "HowTo"
copyright = "2022, Neuroinformatics Unit"
author = "Neuroinformatics Unit"

# The full version, including alpha/beta/rc tags
release = "0.0.1"


# -- General configuration ---------------------------------------------------

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    "sphinx.ext.githubpages",
    "sphinx.ext.autodoc",
    "sphinx.ext.autosummary",
    "sphinx.ext.viewcode",
    "sphinx.ext.intersphinx",
    "sphinx.ext.napoleon",
    "sphinx_design",
    "sphinx_copybutton",
    "myst_parser",
    "numpydoc",
    "nbsphinx",
    "sphinx_gallery.gen_gallery",
]

# Configure the myst parser to enable cool markdown features
myst_enable_extensions = [
    "amsmath",
    "colon_fence",
    "deflist",
    "dollarmath",
    "fieldlist",
    "html_admonition",
    "html_image",
    "linkify",
    "replacements",
    "smartquotes",
    "strikethrough",
    "substitution",
    "tasklist",
]
# Automatically add anchors to markdown headings
myst_heading_anchors = 3

# Add any paths that contain templates here, relative to this directory.
templates_path = ["_templates"]

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = [
    "**.ipynb_checkpoints",
    # to ensure that include files (partial pages) aren't built, exclude them
    # https://github.com/sphinx-doc/sphinx/issues/1965#issuecomment-124732907
    "**/includes/**",
    # exclude .py and .ipynb files in auto_examples generated by sphinx-gallery
    # this is to prevent sphinx from complaining about duplicate source files
    "electrophysiology/example_pipelines/auto_examples_ephys/*.ipynb",
    "electrophysiology/example_pipelines/auto_examples_ephys/*.py",
]

# Ignore certain URLs from being checked
linkcheck_ignore = [
    "https://neuromorpho.org/",
    "https://wiki.ucl.ac.uk/",  # ignore everything on the internal wiki
    "https://linux.die.net/man/1/rsync",
    "https://www.uclb.com/",
    "https://support.zadarastorage.com",
    "https://stackoverflow.com/questions/24447047/remove-git-annex-repository-from-file-tree",
    "https://joinup.ec.europa.eu/collection/eupl/solution/joinup-licensing-assistant/jla-compatibility-checker",
]
# The linkcheck builder will skip verifying that anchors exist when checking
# these URLs (e.g. because they are generated by JavaScript).
linkcheck_anchors_ignore_for_url = [
    "https://gin.g-node.org/G-Node/Info/wiki",
    "https://gin.g-node.org/G-Node/info/wiki",  # ignore both spellings
    "https://github.com/stephenlenzi/npix_lse",  # ignore private repository
]
linkcheck_retries = 2

# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = "pydata_sphinx_theme"
html_title = "HowTo"

# Redirect the webpage to another URL
# Sphinx will create the appropriate CNAME file in the build directory
# https://www.sphinx-doc.org/en/master/usage/extensions/githubpages.html
html_baseurl = "https://howto.neuroinformatics.dev/"

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ["_static"]

html_css_files = [
    "css/custom.css",
]

html_favicon = "_static/logo_light.png"

## Customize the theme
html_theme_options = {
    "icon_links": [
        {
            # Label for this link
            "name": "GitHub",
            # URL where the link will redirect
            "url": "https://github.com/neuroinformatics-unit/HowTo",  # required
            # Icon class (if "type": "fontawesome"), or path to local image (if "type": "local")
            "icon": "fa-brands fa-github",
            # The type of image to be used (see below for details)
            "type": "fontawesome",
        }
    ],
    "logo": {
        "text": "HowTo",
        "image_light": "logo_light.png",
        "image_dark": "logo_dark.png",
    },
    "footer_start": ["footer_start"],
    "footer_end": ["footer_end"],
    "show_prev_next": False
}

# Hide the "Show Source" button
html_show_sourcelink = False

# Configure the code block copy button
# don't copy line numbers, prompts, or console outputs
copybutton_exclude = ".linenos, .gp, .go"

# Configure sphinx-gallery
sphinx_gallery_conf = {
     'examples_dirs': ["electrophysiology/example_pipelines/examples"],   # path to your example scripts
     'gallery_dirs': ["electrophysiology/example_pipelines/auto_examples_ephys"],    # path to where to save gallery generated output
}
